name: rhymebrain
description: A starting point for Dart libraries or applications.
version: 0.0.10
repository: https://github.com/ibotva/rhymebrain-dart

environment:
  sdk: ^3.0.0-edge.042c3f6c76ab82ead5d61192ef0ed075aa0b394f

dependencies:
  http: ^0.13.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
